package model.enums.view

enum class View {
    BUDGET_WEEKLY, BUDGET, YEAR, CALENDAR_DAY, CALENDAR_WEEK, CALENDAR_MONTH, CALENDAR_YEAR,
    TASK_DAILY, TASK_WEEKLY, TASK_DASHBOARD, TASK_PROJECTS, TASK_PROJECT, TASK_LIST,
    MIXED_DAILY, MIXED_WEEKLY, MIXED_DASHBOARD, MIXED_LIST
}